version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: book_management
      MYSQL_USER: rishi
      MYSQL_PASSWORD: password123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  api:
    build: .
    container_name: book_api_container
    restart: always
    depends_on:
      - mysql
    environment:
      DB_NAME: book_management
      DB_USER: rishi
      DB_PASS: password123
      DB_HOST: mysql
      DB_PORT: 3306
      NODE_ENV: production
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
    command: npm start

volumes:
  mysql_data:
