version: "3.8"

services:
  # MySQL Database Service
  mysql:
    image: mysql:8
    container_name: book-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: book_management
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Node.js API Service
  app:
    build: .
    container_name: book-api
    restart: always
    depends_on:
      - mysql
    environment:
      NODE_ENV: production
      PORT: 5000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: P@ssw0rd
      DB_NAME: book_management
      JWT_SECRET: your_secret_key
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["sh", "-c", "npx sequelize-cli db:migrate && npm start"]

volumes:
  mysql_data:
