name: Deploy to VPS

on:
  push:
    branches:
      - main  # Runs only when you push to "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/your-user/book-management-api
          git pull origin main
          docker-compose down
          docker-compose up -d --build
